baseURL = 'https://andysmith.ai/'
languageCode = 'en-us'
title = 'Andy Smith'
theme = 'ananke'
[pagination]
  pagerSize = 30

[params]
  mainSections = ['blog']

[params.ananke]
  show_recent_posts = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'