baseURL = 'https://andysmith.ai/'
languageCode = 'en-us'
title = 'Andy Smith'
theme = 'ananke'
[params]
  mainSections = ['blog']
  recent_posts_number = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'